import { useEffect, useState } from "react";
import { apiUrl, mediaUrl } from "@/lib/api";

export interface ApiMenuCategory {
  id: number;
  nameTr: string;
  nameEn: string;
  sortOrder: number;
}

export interface ApiMenuItem {
  id: number;
  categoryId: number;
  nameTr: string;
  nameEn: string;
  descTr: string;
  descEn: string;
  photoUrl: string | null;
  sortOrder: number;
}

export interface MenuData {
  categories: ApiMenuCategory[];
  items: ApiMenuItem[];
}

const DEFAULT_MENU: MenuData = {
  categories: [
    {
      id: -1,
      nameTr: "Bu Restoranın En Sevilenleri",
      nameEn: "Most Popular",
      sortOrder: 0,
    },
    {
      id: -2,
      nameTr: "SICAK KAHVELER",
      nameEn: "Hot Coffees",
      sortOrder: 1,
    },
    {
      id: -3,
      nameTr: "SICAK AROMALI KAHVELER",
      nameEn: "Hot Flavored Coffees",
      sortOrder: 2,
    },
    {
      id: -4,
      nameTr: "SICAK MATCHA",
      nameEn: "Hot Matcha",
      sortOrder: 3,
    },
    {
      id: -5,
      nameTr: "SPECİAL SICAK İÇECEKLER",
      nameEn: "Special Hot Drinks",
      sortOrder: 4,
    },
    {
      id: -6,
      nameTr: "DOĞAL BİTKİ ÇAYLARI",
      nameEn: "Natural Herbal Teas",
      sortOrder: 5,
    },
    {
      id: -7,
      nameTr: "SOĞUK KAHVELER",
      nameEn: "Cold Coffees",
      sortOrder: 6,
    },
    {
      id: -8,
      nameTr: "SOĞUK AROMALI KAHVELER",
      nameEn: "Cold Flavored Coffees",
      sortOrder: 7,
    },
    {
      id: -9,
      nameTr: "SOĞUK MATCHA",
      nameEn: "Cold Matcha",
      sortOrder: 8,
    },
    {
      id: -10,
      nameTr: "SPECİAL SOĞUK İÇECEKLER",
      nameEn: "Special Cold Drinks",
      sortOrder: 9,
    },
    {
      id: -11,
      nameTr: "SMOTHİEE",
      nameEn: "Smoothies",
      sortOrder: 10,
    },
    {
      id: -12,
      nameTr: "TAZE SIKIM SOĞUK İÇECEKLER",
      nameEn: "Fresh Cold Drinks",
      sortOrder: 11,
    },
    {
      id: -13,
      nameTr: "TAZE SIKIM DETOKS İÇECEKLER",
      nameEn: "Fresh Detox Drinks",
      sortOrder: 12,
    },
    {
      id: -14,
      nameTr: "GLUTENSİZ LEZZETLER",
      nameEn: "Gluten-Free Items",
      sortOrder: 13,
    },
    {
      id: -15,
      nameTr: "PAKET ÇEKİRDEK KAHVELER",
      nameEn: "Packaged Coffee Beans",
      sortOrder: 14,
    },
  ],
  items: [
    {
      id: -1,
      categoryId: -1,
      nameTr: "ICED LATTE",
      nameEn: "ICED LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -2,
      categoryId: -1,
      nameTr: "ICED STRAWBERRY MATCHA LATTE",
      nameEn: "ICED STRAWBERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -3,
      categoryId: -1,
      nameTr: "FLAT WHİTE",
      nameEn: "FLAT WHİTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -4,
      categoryId: -1,
      nameTr: "FILTRE COFFEE",
      nameEn: "FILTRE COFFEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -5,
      categoryId: -2,
      nameTr: "FILTRE COFFEE",
      nameEn: "FILTRE COFFEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -6,
      categoryId: -2,
      nameTr: "DOUBLE ESPRESSO",
      nameEn: "DOUBLE ESPRESSO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -7,
      categoryId: -2,
      nameTr: "BLACK EYE",
      nameEn: "BLACK EYE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -8,
      categoryId: -2,
      nameTr: "AMERICANO",
      nameEn: "AMERICANO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -9,
      categoryId: -2,
      nameTr: "CAPPUCCINO",
      nameEn: "CAPPUCCINO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -10,
      categoryId: -2,
      nameTr: "CAFFE LATTE",
      nameEn: "CAFFE LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -11,
      categoryId: -2,
      nameTr: "LATTE MACCHIATO",
      nameEn: "LATTE MACCHIATO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 6,
    },
    {
      id: -12,
      categoryId: -2,
      nameTr: "BALLI TARÇINLI LATTE",
      nameEn: "BALLI TARÇINLI LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 7,
    },
    {
      id: -13,
      categoryId: -2,
      nameTr: "FLAT WHİTE",
      nameEn: "FLAT WHİTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 8,
    },
    {
      id: -14,
      categoryId: -2,
      nameTr: "CORTADO",
      nameEn: "CORTADO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 9,
    },
    {
      id: -15,
      categoryId: -3,
      nameTr: "MOCHA",
      nameEn: "MOCHA",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -16,
      categoryId: -3,
      nameTr: "WHITE CHOCOLATE MOCHA",
      nameEn: "WHITE CHOCOLATE MOCHA",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -17,
      categoryId: -3,
      nameTr: "CARAMEL LATTE",
      nameEn: "CARAMEL LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -18,
      categoryId: -3,
      nameTr: "LATTE CARAMEL MACCHİATO",
      nameEn: "LATTE CARAMEL MACCHİATO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -19,
      categoryId: -3,
      nameTr: "SALTED CARAMEL LATTE",
      nameEn: "SALTED CARAMEL LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -20,
      categoryId: -3,
      nameTr: "VANİLYA LATTE",
      nameEn: "VANİLYA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -21,
      categoryId: -3,
      nameTr: "HUZELNUT LATTE",
      nameEn: "HUZELNUT LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 6,
    },
    {
      id: -22,
      categoryId: -3,
      nameTr: "TOFFEE NUT LATTE",
      nameEn: "TOFFEE NUT LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 7,
    },
    {
      id: -23,
      categoryId: -3,
      nameTr: "IRİSH LATTE",
      nameEn: "IRİSH LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 8,
    },
    {
      id: -24,
      categoryId: -3,
      nameTr: "TİRAMİSU LATTE",
      nameEn: "TİRAMİSU LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 9,
    },
    {
      id: -25,
      categoryId: -3,
      nameTr: "COCONUT LATTE",
      nameEn: "COCONUT LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 10,
    },
    {
      id: -26,
      categoryId: -3,
      nameTr: "PUMPKİN LATTE",
      nameEn: "PUMPKİN LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 11,
    },
    {
      id: -27,
      categoryId: -3,
      nameTr: "CREME BRULEE LATTE",
      nameEn: "CREME BRULEE LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 12,
    },
    {
      id: -28,
      categoryId: -3,
      nameTr: "CHOCOLATE COOKİE LATTE",
      nameEn: "CHOCOLATE COOKİE LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 13,
    },
    {
      id: -29,
      categoryId: -4,
      nameTr: "MATCHA LATTE",
      nameEn: "MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -30,
      categoryId: -4,
      nameTr: "PORTAKAL ÇİÇEKLİ MATCHA LATTE",
      nameEn: "PORTAKAL ÇİÇEKLİ MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -31,
      categoryId: -4,
      nameTr: "BERRY MATCHA LATTE",
      nameEn: "BERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -32,
      categoryId: -4,
      nameTr: "STRAWBERRY MATCHA LATTE",
      nameEn: "STRAWBERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -33,
      categoryId: -4,
      nameTr: "RASPBERRY MATCHA LATTE",
      nameEn: "RASPBERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -34,
      categoryId: -4,
      nameTr: "RASPBERRY&STRAWBERRY MATCHA LATTE",
      nameEn: "RASPBERRY&STRAWBERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -35,
      categoryId: -4,
      nameTr: "COCONUT MATCHA LATTE",
      nameEn: "COCONUT MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 6,
    },
    {
      id: -36,
      categoryId: -4,
      nameTr: "VANILLA MATCHA LATTE",
      nameEn: "VANILLA MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 7,
    },
    {
      id: -37,
      categoryId: -4,
      nameTr: "IRİSH MATCHA LATTE",
      nameEn: "IRİSH MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 8,
    },
    {
      id: -38,
      categoryId: -4,
      nameTr: "TİRAMİSU MATCHA LATTE",
      nameEn: "TİRAMİSU MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 9,
    },
    {
      id: -39,
      categoryId: -4,
      nameTr: "SALTED CARAMEL MATCHA LATTE",
      nameEn: "SALTED CARAMEL MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 10,
    },
    {
      id: -40,
      categoryId: -4,
      nameTr: "CREME BRULEE MATCHA LATTE",
      nameEn: "CREME BRULEE MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 11,
    },
    {
      id: -41,
      categoryId: -5,
      nameTr: "HOT CHOCOLATE",
      nameEn: "HOT CHOCOLATE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -42,
      categoryId: -6,
      nameTr: "ADAÇAYI",
      nameEn: "ADAÇAYI",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -43,
      categoryId: -6,
      nameTr: "IHLAMUR",
      nameEn: "IHLAMUR",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -44,
      categoryId: -6,
      nameTr: "KIŞ ÇAYI",
      nameEn: "KIŞ ÇAYI",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -45,
      categoryId: -6,
      nameTr: "YEŞİL ÇAY",
      nameEn: "YEŞİL ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -46,
      categoryId: -6,
      nameTr: "JASMINE PEARLS - YASEMİNLİ YEŞİL ÇAY",
      nameEn: "JASMINE PEARLS - YASEMİNLİ YEŞİL ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -47,
      categoryId: -6,
      nameTr: "GINGER TWIST - AYVA AROMALI YEŞİL ÇAY",
      nameEn: "GINGER TWIST - AYVA AROMALI YEŞİL ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -48,
      categoryId: -6,
      nameTr: "MORGENTAU - PEYGAMBER ÇİÇEĞİ ve MANGOLU YEŞİL ÇAY",
      nameEn: "MORGENTAU - PEYGAMBER ÇİÇEĞİ ve MANGOLU YEŞİL ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 6,
    },
    {
      id: -49,
      categoryId: -6,
      nameTr: "HUCKLEBERRY FRİEND - YABAN MERSİNLİ YEŞİL ÇAY",
      nameEn: "HUCKLEBERRY FRİEND - YABAN MERSİNLİ YEŞİL ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 7,
    },
    {
      id: -50,
      categoryId: -6,
      nameTr: "REFRESHING MINT - NANELİ BİTKİ ÇAYI",
      nameEn: "REFRESHING MINT - NANELİ BİTKİ ÇAYI",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 8,
    },
    {
      id: -51,
      categoryId: -6,
      nameTr: "CHINESE SPRING TEA - ÇARKIFELEK MEYVELİ BEYAZ ÇAY",
      nameEn: "CHINESE SPRING TEA - ÇARKIFELEK MEYVELİ BEYAZ ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 9,
    },
    {
      id: -52,
      categoryId: -6,
      nameTr: "WHITE MELON - KAVUNLU BEYAZ ÇAY",
      nameEn: "WHITE MELON - KAVUNLU BEYAZ ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 10,
    },
    {
      id: -53,
      categoryId: -6,
      nameTr: "EARL GREY - BERGAMOTLU SİYAH ÇAY",
      nameEn: "EARL GREY - BERGAMOTLU SİYAH ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 11,
    },
    {
      id: -54,
      categoryId: -6,
      nameTr: "MASALA CHAI TEA - BAHARATLI ÇAY",
      nameEn: "MASALA CHAI TEA - BAHARATLI ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 12,
    },
    {
      id: -55,
      categoryId: -6,
      nameTr: "IRİSH WHİSKEY CREAM - MALT WİSKİ AROMALI SİYAH ÇAY",
      nameEn: "IRİSH WHİSKEY CREAM - MALT WİSKİ AROMALI SİYAH ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 13,
    },
    {
      id: -56,
      categoryId: -6,
      nameTr: "APRICOT PEACH OOLONG - ŞEFTALİ ve KADİFE ÇİÇEKLİ ÇAY",
      nameEn: "APRICOT PEACH OOLONG - ŞEFTALİ ve KADİFE ÇİÇEKLİ ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 14,
    },
    {
      id: -57,
      categoryId: -6,
      nameTr: "TROPICAL SUN - TROPIC MEYVE ÇAYI",
      nameEn: "TROPICAL SUN - TROPIC MEYVE ÇAYI",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 15,
    },
    {
      id: -58,
      categoryId: -6,
      nameTr: "GET TTHE POWER TEA - FRENK ÜZÜMLÜ ve PORTAKALLI ÇAY",
      nameEn: "GET TTHE POWER TEA - FRENK ÜZÜMLÜ ve PORTAKALLI ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 16,
    },
    {
      id: -59,
      categoryId: -6,
      nameTr: "CHILL OUT WITH HERBS - BÖĞÜRTLEN VE ROOIBOSLU BİTKİ ÇAYI",
      nameEn: "CHILL OUT WITH HERBS - BÖĞÜRTLEN VE ROOIBOSLU BİTKİ ÇAYI",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 17,
    },
    {
      id: -60,
      categoryId: -6,
      nameTr: "ROOIBOS VANILLA - VANİLYALI KIRMIZI ÇAY",
      nameEn: "ROOIBOS VANILLA - VANİLYALI KIRMIZI ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 18,
    },
    {
      id: -61,
      categoryId: -6,
      nameTr: "ROOIBOS CREAM ORANGE - PORTAKAL ve VANİLYALI KIRMIZI ÇAY",
      nameEn: "ROOIBOS CREAM ORANGE - PORTAKAL ve VANİLYALI KIRMIZI ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 19,
    },
    {
      id: -62,
      categoryId: -6,
      nameTr: "ROOIBOS CHOCOLATE - ÇİKOLATALI ve VANİLYALI KIRMIZI ÇAY",
      nameEn: "ROOIBOS CHOCOLATE - ÇİKOLATALI ve VANİLYALI KIRMIZI ÇAY",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 20,
    },
    {
      id: -63,
      categoryId: -7,
      nameTr: "COLD BREW",
      nameEn: "COLD BREW",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -64,
      categoryId: -7,
      nameTr: "ICED AMERICANO",
      nameEn: "ICED AMERICANO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -65,
      categoryId: -7,
      nameTr: "ICED LATTE",
      nameEn: "ICED LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -66,
      categoryId: -7,
      nameTr: "ICED CAPPICINO",
      nameEn: "ICED CAPPICINO",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -67,
      categoryId: -7,
      nameTr: "ICED FLAT WHITE",
      nameEn: "ICED FLAT WHITE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -68,
      categoryId: -7,
      nameTr: "ICED VANİLYA FRAPPE",
      nameEn: "ICED VANİLYA FRAPPE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -69,
      categoryId: -7,
      nameTr: "ICED CHOCOLATE FRAPPE",
      nameEn: "ICED CHOCOLATE FRAPPE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 6,
    },
    {
      id: -70,
      categoryId: -8,
      nameTr: "ICED VANİLYA FRAPPE",
      nameEn: "ICED VANİLYA FRAPPE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -71,
      categoryId: -8,
      nameTr: "ICED CHOCOLATE FRAPPE",
      nameEn: "ICED CHOCOLATE FRAPPE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -72,
      categoryId: -8,
      nameTr: "ICED MOCHA",
      nameEn: "ICED MOCHA",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -73,
      categoryId: -8,
      nameTr: "ICED WHITE CHOCOLATE MOCHA",
      nameEn: "ICED WHITE CHOCOLATE MOCHA",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -74,
      categoryId: -8,
      nameTr: "ICED CARAMEL LATTE",
      nameEn: "ICED CARAMEL LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -75,
      categoryId: -8,
      nameTr: "ICED SALTED CARAMEL LATTE",
      nameEn: "ICED SALTED CARAMEL LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -76,
      categoryId: -8,
      nameTr: "ICED VANİLYA LATTE",
      nameEn: "ICED VANİLYA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 6,
    },
    {
      id: -77,
      categoryId: -8,
      nameTr: "ICED HUZELNUT LATTE",
      nameEn: "ICED HUZELNUT LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 7,
    },
    {
      id: -78,
      categoryId: -8,
      nameTr: "ICED TOFFEE NUT LATTE",
      nameEn: "ICED TOFFEE NUT LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 8,
    },
    {
      id: -79,
      categoryId: -8,
      nameTr: "ICED IRİSH LATTE",
      nameEn: "ICED IRİSH LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 9,
    },
    {
      id: -80,
      categoryId: -8,
      nameTr: "ICED TİRAMİSU LATTE",
      nameEn: "ICED TİRAMİSU LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 10,
    },
    {
      id: -81,
      categoryId: -8,
      nameTr: "ICED COCONUT LATTE",
      nameEn: "ICED COCONUT LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 11,
    },
    {
      id: -82,
      categoryId: -8,
      nameTr: "ICED PUMPKİN LATTE",
      nameEn: "ICED PUMPKİN LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 12,
    },
    {
      id: -83,
      categoryId: -8,
      nameTr: "ICED CREME BRULEE LATTE",
      nameEn: "ICED CREME BRULEE LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 13,
    },
    {
      id: -84,
      categoryId: -8,
      nameTr: "ICED CHOCOLATE COOKİE LATTE",
      nameEn: "ICED CHOCOLATE COOKİE LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 14,
    },
    {
      id: -85,
      categoryId: -9,
      nameTr: "ICED MATCHA LATTE",
      nameEn: "ICED MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -86,
      categoryId: -9,
      nameTr: "PORTAKAL ÇİÇEKLİ ICED MATCHA LATTE",
      nameEn: "PORTAKAL ÇİÇEKLİ ICED MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -87,
      categoryId: -9,
      nameTr: "ICED RASPBERRY MATCHA LATTE",
      nameEn: "ICED RASPBERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -88,
      categoryId: -9,
      nameTr: "ICED VANILLA MATCHA LATTE",
      nameEn: "ICED VANILLA MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -89,
      categoryId: -9,
      nameTr: "ICED BERRY MATCHA LATTE",
      nameEn: "ICED BERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -90,
      categoryId: -9,
      nameTr: "ICED STRAWBERRY MATCHA LATTE",
      nameEn: "ICED STRAWBERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -91,
      categoryId: -9,
      nameTr: "ICED MANGO&PEACH MATCHA LATTE",
      nameEn: "ICED MANGO&PEACH MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 6,
    },
    {
      id: -92,
      categoryId: -9,
      nameTr: "ICED RASPBERRY&STRAWBERRY MATCHA LATTE",
      nameEn: "ICED RASPBERRY&STRAWBERRY MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 7,
    },
    {
      id: -93,
      categoryId: -9,
      nameTr: "ICED COCONUT MATCHA LATTE",
      nameEn: "ICED COCONUT MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 8,
    },
    {
      id: -94,
      categoryId: -9,
      nameTr: "ICED IRISH MATCHA LATTE",
      nameEn: "ICED IRISH MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 9,
    },
    {
      id: -95,
      categoryId: -9,
      nameTr: "ICED TİRAMİSU MATCHA LATTE",
      nameEn: "ICED TİRAMİSU MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 10,
    },
    {
      id: -96,
      categoryId: -9,
      nameTr: "ICED CREME BRULEE MATCHA LATTE",
      nameEn: "ICED CREME BRULEE MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 11,
    },
    {
      id: -97,
      categoryId: -9,
      nameTr: "ICED SALTED CARAMEL MATCHA LATTE",
      nameEn: "ICED SALTED CARAMEL MATCHA LATTE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 12,
    },
    {
      id: -98,
      categoryId: -10,
      nameTr: "EV YAPIMI ÇİLEKLİ LİMONATA",
      nameEn: "EV YAPIMI ÇİLEKLİ LİMONATA",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -99,
      categoryId: -10,
      nameTr: "EV YAPIMI LİMONATA - (HOMEMADELEMONADE)",
      nameEn: "EV YAPIMI LİMONATA - (HOMEMADELEMONADE)",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -100,
      categoryId: -10,
      nameTr: "COOL LİME",
      nameEn: "COOL LİME",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -101,
      categoryId: -10,
      nameTr: "BLACKBERRY HİBİSKUS",
      nameEn: "BLACKBERRY HİBİSKUS",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -102,
      categoryId: -11,
      nameTr: "STRAWBERRY SMOTHİEE",
      nameEn: "STRAWBERRY SMOTHİEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -103,
      categoryId: -11,
      nameTr: "PEACH SMOTHİEE",
      nameEn: "PEACH SMOTHİEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -104,
      categoryId: -11,
      nameTr: "BLUEBERRY SMOTHİEE",
      nameEn: "BLUEBERRY SMOTHİEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -105,
      categoryId: -11,
      nameTr: "MANGO SMOTHİEE",
      nameEn: "MANGO SMOTHİEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -106,
      categoryId: -11,
      nameTr: "ORMAN MEYVELİ SMOTHİEE",
      nameEn: "ORMAN MEYVELİ SMOTHİEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -107,
      categoryId: -11,
      nameTr: "PEACH-MANGO SMOTHİEE",
      nameEn: "PEACH-MANGO SMOTHİEE",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 5,
    },
    {
      id: -108,
      categoryId: -12,
      nameTr: "EV YAPIMI LİMONATA - (HOMEMADELEMONADE)",
      nameEn: "EV YAPIMI LİMONATA - (HOMEMADELEMONADE)",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -109,
      categoryId: -12,
      nameTr: "EV YAPIMI ÇİLEKLİ LİMONATA",
      nameEn: "EV YAPIMI ÇİLEKLİ LİMONATA",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -110,
      categoryId: -12,
      nameTr: "TAZE SIKIM PORTAKAL SUYU",
      nameEn: "TAZE SIKIM PORTAKAL SUYU",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -111,
      categoryId: -12,
      nameTr: "TAZE SIKIM YEŞİL ELMA SUYU",
      nameEn: "TAZE SIKIM YEŞİL ELMA SUYU",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -112,
      categoryId: -13,
      nameTr: "GOLDIE DRINKIE - TAZE SIKIM DETOKS",
      nameEn: "GOLDIE DRINKIE - TAZE SIKIM DETOKS",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -113,
      categoryId: -13,
      nameTr: "GREENIE DRINKIE - TAZE SIKIM DETOKS",
      nameEn: "GREENIE DRINKIE - TAZE SIKIM DETOKS",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -114,
      categoryId: -13,
      nameTr: "PINKIE DRINKIE - TAZE SIKIM DETOKS",
      nameEn: "PINKIE DRINKIE - TAZE SIKIM DETOKS",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -115,
      categoryId: -13,
      nameTr: "GREENIE BLAZE DRINKIE - TAZE SIKIM DETOKS",
      nameEn: "GREENIE BLAZE DRINKIE - TAZE SIKIM DETOKS",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -116,
      categoryId: -13,
      nameTr: "GREENIE PURIFICATION DRINKIE - TAZE SIKIM DETOKS",
      nameEn: "GREENIE PURIFICATION DRINKIE - TAZE SIKIM DETOKS",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
    {
      id: -117,
      categoryId: -14,
      nameTr: "GRANOLA 250 Gr. (PAKET)",
      nameEn: "GRANOLA 250 Gr. (PAKET)",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -118,
      categoryId: -15,
      nameTr: "GRANOLA 250 Gr. (PAKET)",
      nameEn: "GRANOLA 250 Gr. (PAKET)",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 0,
    },
    {
      id: -119,
      categoryId: -15,
      nameTr: "SANTOS ESPRESSO ÇEKİRDEK KAHVE 250Gr.",
      nameEn: "SANTOS ESPRESSO ÇEKİRDEK KAHVE 250Gr.",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 1,
    },
    {
      id: -120,
      categoryId: -15,
      nameTr: "SANTOS ÇEKİRDEK FİLTRE KAHVE 250Gr.",
      nameEn: "SANTOS ÇEKİRDEK FİLTRE KAHVE 250Gr.",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 2,
    },
    {
      id: -121,
      categoryId: -15,
      nameTr: "SANTOS ESPRESSO ÇEKİRDEK KAHVE 1000Gr.",
      nameEn: "SANTOS ESPRESSO ÇEKİRDEK KAHVE 1000Gr.",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 3,
    },
    {
      id: -122,
      categoryId: -15,
      nameTr: "SANTOS FİLTRE ÇEKİRDEK KAHVE 1000Gr.",
      nameEn: "SANTOS FİLTRE ÇEKİRDEK KAHVE 1000Gr.",
      descTr: "",
      descEn: "",
      photoUrl: null,
      sortOrder: 4,
    },
  ],
};

export function useMenuData() {
  const [menuData, setMenuData] = useState<MenuData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(apiUrl("/api/menu"))
      .then((r) => r.json())
      .then((data: MenuData) => {
        if (data?.categories?.length > 0) {
          setMenuData({
            ...data,
            items: data.items.map((item) => ({
              ...item,
              photoUrl: mediaUrl(item.photoUrl),
            })),
          });
        } else {
          setMenuData(DEFAULT_MENU);
        }
      })
      .catch(() => setMenuData(DEFAULT_MENU))
      .finally(() => setLoading(false));
  }, []);

  return { menuData: menuData ?? DEFAULT_MENU, loading };
}

export { DEFAULT_MENU };
